#!/bin/sh
echo "Running kotlinter"
echo "Checking code..."
./gradlew lintKotlin
if [ $? -ne 0 ]; then
  echo 'Running kotlinter'
  echo 'Formatting code...'
  ./gradlew formatKotlin
  if [ $? -ne 1 ]; then
    git add .
    git commit -m 'Fixing lint'
  fi
  exit 1;
fi