/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 * como olvidar cuando Gorro tuvo su momento de iluminacion y puso "null" en el live de hoy XD
 * aguacate no palta XD
 */
package com.kotlinerskt.cli.giskt

fun main(args: Array<String>) {
    Giskt().main(args)
}
